UCRMS_MVC/Controllers/AllocateClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCRMS_MVC.DBGateway;
using UCRMS_MVC.DBManager;
using UCRMS_MVC.Models;

namespace UCRMS_MVC.Controllers
{
    public class AllocateClassRoomController : Controller
    {
        DepartmentGateway aDepartmentGateway=new DepartmentGateway();
        CourseGateway aCourseGateway=new CourseGateway();
        AllocateRoomManager allocateRoomManager=new AllocateRoomManager();
        //private object dynamic;
        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Allocate()
        {
            ViewBag.AllDepartment = aCourseGateway.GetAllDepartment();
            ViewBag.allCourses = aCourseGateway.GetAllCourse();
            ViewBag.allRoom = allocateRoomManager.GetAllRoom();
            ViewBag.allDays = allocateRoomManager.GetAllDays();
            return View();
        }
        [HttpPost]
        public ActionResult Allocate(AllocationClassRoom allocationClass)
        {
            ViewBag.AllDepartment = aCourseGateway.GetAllDepartment();
            ViewBag.allCourses = aCourseGateway.GetAllCourse();
            ViewBag.allRoom = allocateRoomManager.GetAllRoom();
            ViewBag.allDays = allocateRoomManager.GetAllDays();
            ViewBag.message = allocateRoomManager.Allocate(allocationClass)
             ? (dynamic)new HtmlString("<div class='alert alert-success'><strong>Success!</strong> Classroom has been allocated successfully. </div>")
             : (dynamic)new HtmlString("<div class='alert alert-danger'><strong>Error!</strong> Failed to save Information.</div>");
            ModelState.Clear();
           return View();
        }
        public JsonResult GetCourseByDepartmentId(int departmentId)
        {
            List<Course> listCourses = aCourseGateway.GetCourseByDepartmentId(departmentId);
            return Json(listCourses, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult ViewClassSchedule()
        {
            ViewBag.AllDepartment = aCourseGateway.GetAllDepartment();
            return View();
        }

        public JsonResult GetClassScheduleDepartmentId(int departmentId)
        {
            var courses = allocateRoomManager.GetCourseByDepartmentId(departmentId);
             List<object> ClsSchedule= new List<object>();
            foreach (var data in courses)
            {
                var scheduleInfo = allocateRoomManager.GetClassSchedule(departmentId, data.CourseId);
                scheduleInfo = (scheduleInfo == "") ? "Not Scheduled Yet" : scheduleInfo;

                var ClassSche = new
                {
                    CourseCode = data.CourseCode,
                    CourseName = data.CourseName,
                    ScheduleInfo = scheduleInfo
                };
                ClsSchedule.Add(ClassSche);
               
            }
            return Json(ClsSchedule, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UnAllocationAllRoom()
        {
            return View();
        }

        public JsonResult AjaxUnAllocationAllRoom()
        {
            var result = allocateRoomManager.UnAllocationAllRoom();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
	}
}

UCRMS_MVC/Views/AllocateClassRoom/Allocate.cshtml
@using UCRMS_MVC.Models
@model UCRMS_MVC.Models.AllocationClassRoom
@{
    Layout = null;
    List<Department> aDepartments = ViewBag.AllDepartment;
    List<Course> aCourses = ViewBag.allCourses;
    List<Room> aRooms = ViewBag.allRoom;
    List<Day> aDays = ViewBag.allDays;
 
   }
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UCRMS</title>
    <meta name="description" content="A description of your website">
    <meta name="keywords" content="keyword1, keyword2, keyword3">
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link href="~/Minimal-jQuery-Time-Picker-Plugin-with-jQuery-TimePicki/css/timepicki.css" rel="stylesheet" />
    <link href="~/Minimal-jQuery-Time-Picker-Plugin-with-jQuery-TimePicki/css/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/Minimal-jQuery-Time-Picker-Plugin-with-jQuery-TimePicki/js/jquery.min.js"></script>
    <script src="~/Minimal-jQuery-Time-Picker-Plugin-with-jQuery-TimePicki/js/timepicki.js"></script>
    <style>
        .ErrorMessage {
            color: red;
            font-style: italic;
        }
    </style>
</head>
<body>

    <div id="wrapper">

        <div id="header">

            <div class="banner_img">
                <h1>University Course and Result Management System </h1>
            </div>
            </div>
        <div class="navigation navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="#">Home</a></li>
                <li>@Html.ActionLink("Department", "Index", "Department")</li>
                <li>@Html.ActionLink("Course", "SaveCourse", "Course")</li>
                <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>
                <li>@Html.ActionLink("Student", "Index", "Student")</li>
                <li>@Html.ActionLink("Enroll Course", "Enroll", "Enroll")</li>
                <li>@Html.ActionLink("Allocate Rooms", "Index", "AllocateClassRoom")</li>
                <li><a href="#">Schedule</a></li>
            </ul>
        </div>
       <div id="page_content">
            @using (Html.BeginForm())
            {
                <form>
                    <fieldset>
                        <legend><h3>Allocate Room:</h3></legend>
                        <br />
                        <table>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.DeptId)
                                </td>
                                <td>
                                    <select name="DeptId" id="DeptId">
                                        <option value="">--Select One--</option>
                                        @foreach (Department department in aDepartments)
                                        {
                                            <option value="@department.DeptId">@department.DeptCode</option>
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.CourseId)
                                </td>
                                <td>
                                    <select name="CourseId" id="CourseId">
                                        <option value="">--Select One--</option>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.RoomId)
                                </td>
                                <td>
                                    <select name="RoomId" id="RoomId">
                                        <option value="">--Select One--</option>
                                        @foreach (Room room in aRooms)
                                        {
                                            <option value="@room.RoomId">@room.RoomNo</option>
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.DayId)
                                </td>
                                <td>
                                    <select name="DayId" id="DayId">
                                        <option value="">--Select One--</option>
                                        @foreach (Day day in aDays)
                                        {
                                            <option value="@day.DayId">@day.DayName</option>
                                        }
                                    </select>
                                </td>
                            </tr>

                            <tr>
                                <td>@Html.LabelFor(d => d.StartTime) </td>
                                <td>@Html.TextBoxFor(d => d.StartTime)</td>
                                <td>@Html.ValidationMessageFor(m => m.StartTime)</td>
                               </tr>
                            <tr>
                                <td>@Html.LabelFor(d => d.EndTime) </td>
                                <td>@Html.TextBoxFor(d => d.EndTime)</td>
                                <td>@Html.ValidationMessageFor(m => m.EndTime)</td>
                                @*<input type="text" name="time">*@
                            </tr>
                            <tr class="message">
                                <td colspan="3">
                                    @if (ViewBag.message != null)
                                    {
                                        @ViewBag.message
                                    }
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @*<input type="submit" value="Allocate"/>*@
                                    <button type="submit" value="Allocate"  >Allocate</button>
                               
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.ActionLink("Back", "Index", "AllocateClassRoom")
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                </form>
            }
            <div class="clear"></div>
            <!--start footer from here-->
            <div id="footer">
                </div>
        </div>
    </div>
    @*<script src="~/Scripts/jquery-2.2.0.js"></script>*@
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $(document).ready(function() {
            $("#DeptId").change(function () {
                var Dept = $("#DeptId").val();
                $("#CourseId").empty();
                var json = { departmentId: Dept };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByDepartmentId", "AllocateClassRoom")',
                    contentType: "application/json; cahrset=utf-8",
                    data: JSON.stringify(json),

                    success: function (data) {
                        $("#CourseId").append('<option value=' + null + '>Select Course ...</option>');
                        //alert(data);
                           $.each(data, function(key, value) {
                               $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseCode + '</option>');
                        });
                    }
                });
            });
        });
    </script>
    <script >
        $(function () {
            $("input").timepicki();
        });
    </script>

</body>
</html>

UCRMS_MVC/Views/AllocateClassRoom/Index.cshtml
@using UCRMS_MVC.Models
@model UCRMS_MVC.Models.ViewResultByRegNo

@{
    Layout = null;
    List<Student> allStudents = ViewBag.allStudents;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>UCRMS</title>
    <meta name="description" content="A description of your website">
    <meta name="keywords" content="keyword1, keyword2, keyword3">
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link href="~/Content/jquery.datepick.css" rel="stylesheet" />
    <style>
        .ErrorMessage {
            color: red;
            font-style: italic;
        }
    </style>
</head>
<body>

    <div id="wrapper">

        <div id="header">

            <div class="banner_img">
                <h1>University Course and Result Management System </h1>
            </div>

        </div>

        <div class="navigation navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Department", "Index", "Department")</li>
                <li>@Html.ActionLink("Course", "Index", "Course")</li>
                <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>
                <li>@Html.ActionLink("Student", "Index", "Student")</li>
                <li>@Html.ActionLink("Enroll Course", "Enroll", "Enroll")</li>
                <li>@Html.ActionLink("Allocate Rooms", "Index", "AllocateClassRoom")</li>
            </ul>
        </div>
       
        <div id="page_content">
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    <h3>Class Room Allocation</h3>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-header">
                    <li>@Html.ActionLink("Allocate ClassRooms", "Allocate", "AllocateClassRoom")</li>
                    <li>@Html.ActionLink("View Class Room Schedule", "ViewClassSchedule", "AllocateClassRoom")</li>
                    <li>@Html.ActionLink("UnAllocation All Class Room", "UnAllocationAllRoom", "AllocateClassRoom")</li>
                   </ul>
            </div>
            <div class="clear"></div>

            <!--start footer from here-->
            <div id="footer">

            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    
   </body>
</html>

UCRMS_MVC/Views/AllocateClassRoom/UnAllocationAllRoom.cshtml
@using System.ServiceModel.Channels
@using UCRMS_MVC.Models

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>UCRMS</title>
    <meta name="description" content="A description of your website">
    <meta name="keywords" content="keyword1, keyword2, keyword3">
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link href="~/Content/jquery.datepick.css" rel="stylesheet" />
    <style>
        .ErrorMessage {
            color: red;
            font-style: italic;
        }
    </style>
</head>
<body>

    <div id="wrapper">

        <div id="header">

            <div class="banner_img">
                <h1>University Course and Result Management System </h1>
            </div>

        </div>

        <div class="navigation navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Department", "Index", "Department")</li>
                <li>@Html.ActionLink("Course", "Index", "Course")</li>
                <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>
                <li>@Html.ActionLink("Student", "Index", "Student")</li>
                <li>@Html.ActionLink("Enroll Course", "Enroll", "Enroll")</li>
                <li>@Html.ActionLink("Allocate Rooms", "Index", "AllocateClassRoom")</li>
            </ul>
        </div>
   
        <div style="text-align: center;background: silver;font-size: larger;" >
            <input id="UnallocateButton" type="button" value="Unallocate All Classrooms" style="width: 250px;height: 200px; margin: 20px auto;font-size: larger;" />
        </div>
        <div>
            <tr>
                <td>
                    @Html.ActionLink("Back", "Index", "AllocateClassRoom")
                </td>
            </tr>
        </div>
      
    </div>
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $(document).ready(function () {
            $("#UnallocateButton").click(function () {
                var res = confirm("Are you sure to unallocate all classrooms info?");
                if (res == false) {
                    return false;
                } else {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("AjaxUnAllocationAllRoom", "AllocateClassRoom")',
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data) {
                                alert("All classrooms has been unallocated successfully.");
                            } else {
                                alert("Unable to unallocate, try again.");
                            }
                        }
                    });
                }
            });
        });
    </script>
</body>
</html>

UCRMS_MVC/Views/AllocateClassRoom/ViewClassSchedule.cshtml
@using UCRMS_MVC.Models
@model UCRMS_MVC.Models.AllocationClassRoom
@{
    Layout = null;
    List<Department> aDepartments = ViewBag.AllDepartment;
    //string message = ViewBag.message;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UCRMS</title>
    <meta name="description" content="A description of your website">
    <meta name="keywords" content="keyword1, keyword2, keyword3">
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <style>
        .ErrorMessage {
            color: red;
            font-style: italic;
        }
    </style>
</head>
<body>

    <div id="wrapper">

        <div id="header">

            <div class="banner_img">
                <h1>University Course and Result Management System </h1>
            </div>
        </div>
        <div class="navigation navbar-collapse collapse">
            <ul class="nav navbar-nav">
               <li>@Html.ActionLink("Department", "Index", "Department")</li>
                <li>@Html.ActionLink("Course", "Index", "Course")</li>
                <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>
                <li>@Html.ActionLink("Student", "Index", "Student")</li>
                <li>@Html.ActionLink("Enroll Course", "Enroll", "Enroll")</li>
                <li>@Html.ActionLink("Allocate Rooms", "Index", "AllocateClassRoom")</li>
             </ul>
        </div>
      
        <div id="page_content">
            @using (Html.BeginForm())
            {
                <form>
                    <fieldset>
                        <legend><h3>View ClassRoom And Allocation Room Information:</h3></legend>
                        <br />
                        <table>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.DeptId)
                                </td>
                                <td>
                                    <select name="DeptId" id="DeptId">
                                        <option value="">--Select One--</option>
                                        @foreach (Department department in aDepartments)
                                        {
                                            <option value="@department.DeptId">@department.DeptCode</option>
                                        }
                                    </select>
                                </td>
                            </tr>
                          
                        </table>
                        <table id="SchduleTable" class="table1">
                            <thead>
                                <tr>
                                    <th>Course Coude</th>
                                    <th>Name</th>
                                    <th>Schedule Info</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                        <tr>
                            <td>
                                @Html.ActionLink("Back", "Index", "AllocateClassRoom")
                            </td>
                        </tr>
                    </fieldset>
                </form>
            }
            <div class="clear"></div>
            <!--start footer from here-->
            <div id="footer">
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $(document).ready(function () {
            $("#DeptId").change(function () {
                var Dept = $("#DeptId").val();
                $('#SchduleTable tbody').empty();
                var json = { departmentId: Dept };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetClassScheduleDepartmentId", "AllocateClassRoom")',
                    contentType: "application/json; cahrset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);
                        $.each(data, function (key, value) {

                            $('#SchduleTable tbody').append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</d><td>' + value.ScheduleInfo+'</td><tr>');
                        });
                    }
                });
            });
        });
    </script>
</body>
</html>