UCRMS_MVC/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace UCRMS_MVC.Models
{
    public class Course
    {
        public int CourseId { get; set; }
        [Required(ErrorMessage = "Provide Course Code")]
        [DisplayName("Course Code")]
        [StringLength(10, MinimumLength = 5, ErrorMessage = "Course Code should be 5 to 10 charcters.")]
        public string CourseCode { get; set; }
        [Required(ErrorMessage = "Provide Course Name")]
        [DisplayName("Course Name")]
        public string CourseName { get; set; }
        [Required(ErrorMessage = "Provide Course Credit")]
        [DisplayName("Course Credit")]
        [Range(.5,5 ,ErrorMessage = "Course Credit should be .5 to 5 in reange")]
        public decimal CourseCredit { get; set; }
        public string Description { get; set; }
        [DisplayName("Department")]
        public int DeptId { get; set; }
        [DisplayName("Semester")]
        public int SemesterId { get; set; }

    }

    }

UCRMS_MVC/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCRMS_MVC.DBManager;
using UCRMS_MVC.Models;

namespace UCRMS_MVC.Controllers
{
    public class CourseController : Controller
    {
        CourseManager aCourseManager=new CourseManager();

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult SaveCourse()
        {
            List<Semester> aSemesters = aCourseManager.GetAllSemester();
            List<Department> aDepartments = aCourseManager.GetAllDepartment();
            ViewBag.aSemesters = aSemesters;
            ViewBag.aDepartments = aDepartments;
            return View();
        }
        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {
           
            List<Semester> aSemesters = aCourseManager.GetAllSemester();
            List<Department> aDepartments = aCourseManager.GetAllDepartment();
            ViewBag.aSemesters = aSemesters;
            ViewBag.aDepartments = aDepartments;
            ViewBag.message = aCourseManager.SaveCourse(course);
            ModelState.Clear();
            return View();
        }

        public ActionResult UnAssignAllCourses()
        {
            return View();
        }

        public JsonResult AjaxUnAssignAllCourses()
        {
            var result = aCourseManager.UnAssignAllCourses();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
	}
}

UCRMS_MVC/Controllers/EnrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCRMS_MVC.DBGateway;
using UCRMS_MVC.DBManager;
using UCRMS_MVC.Models;

namespace UCRMS_MVC.Controllers
{
    public class EnrollController : Controller
    {
        EnrollManager aEnrollManager=new EnrollManager();
        CourseManager aCourseManager=new CourseManager();
        EnrollGateway aEnrollGateway=new EnrollGateway();
        public ActionResult Enroll()
        {
            ViewBag.allStudents = aEnrollManager.GetAllStudent();
            
            return View();
        }
        [HttpPost]
        public ActionResult Enroll(Enroll enroll)
        {
            ViewBag.allStudents = aEnrollManager.GetAllStudent();
            ViewBag.message = aEnrollManager.EnroolStudent(enroll);
            ModelState.Clear();
            return View();
        }
       public JsonResult GetStudentDetailByRegNo(string regNo)
        {
            List<GetStudentByRegNo> aStudents = aEnrollGateway.GetStudentDetailByRegNo(regNo);
            return Json(aStudents, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllCoursesByRegNo(string regNo)
        {
            List<Course> courses = aEnrollGateway.GetAllCoursesByRegNo(regNo);
            return Json(courses, JsonRequestBehavior.AllowGet);

       }

      
	}
}

UCRMS_MVC/Views/Course/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UCRMS</title>
    <meta name="description" content="A description of your website">
    <meta name="keywords" content="keyword1, keyword2, keyword3">

    <link href="~/StyleSheet.css" rel="stylesheet" />
</head>
<body>

    <div id="wrapper">

        <div id="header">

            <div class="banner_img">
                <h1>University Course and Result Management System </h1>
            </div>
        </div>

        <div class="navigation">
            <ul>
                <li>@Html.ActionLink("Department", "Index", "Department")</li>
                <li>@Html.ActionLink("Course", "Index", "Course")</li>
                <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>
                <li>@Html.ActionLink("Student", "Index", "Student")</li>
                <li>@Html.ActionLink("Enroll Course", "Enroll", "Enroll")</li>
                <li>@Html.ActionLink("Allocate Rooms", "Index", "AllocateClassRoom")</li>
            </ul>
        </div>

        <div id="page_content">
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    <h3>Course Detail</h3>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-header">
                    <li>@Html.ActionLink("Save Course", "SaveCourse", "Course")</li>
                    <li>@Html.ActionLink("UnAssign All Course", "UnAssignAllCourses", "Course")</li>

                </ul>
            </div>
            <div class="clear"></div>

            <!--start footer from here-->
            <div id="footer">

            </div>
        </div>
    </div>

</body>
</html>

UCRMS_MVC/Views/Course/SaveCourse.cshtml
@using UCRMS_MVC.Models
@model UCRMS_MVC.Models.Course
@{
    Layout = null;
    List<Department> aDepartments = ViewBag.aDepartments;
    List<Semester> aSemesters = ViewBag.aSemesters;
    string message = ViewBag.message;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>UCRMS</title>
    <meta name="description" content="A description of your website">
    <meta name="keywords" content="keyword1, keyword2, keyword3">
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <style>
        .ErrorMessage {
            color: red;
            font-style: italic;
        }
    </style>
</head>
<body>

    <div id="wrapper">

        <div id="header">

            <div class="banner_img">
                <h1>University Course and Result Management System </h1>
            </div>

        </div>

        <div class="navigation navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Department", "Index", "Department")</li>
                <li>@Html.ActionLink("Course", "Index", "Course")</li>
                <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>
                <li>@Html.ActionLink("Student", "Index", "Student")</li>
                <li>@Html.ActionLink("Enroll Course", "Enroll", "Enroll")</li>
                <li>@Html.ActionLink("Allocate Rooms", "Index", "AllocateClassRoom")</li>
            </ul>
        </div>

        
        <div id="page_content">
            @using (Html.BeginForm())
            {
                <form>
                    <fieldset>
                        <legend><h3>Save Course:</h3></legend>
                        <br />
                        <table>
                            <tr>
                                <td>
                                    @Html.LabelFor(x => x.CourseCode)
                                </td>
                                <td>
                                    @Html.TextBoxFor(x => x.CourseCode)
                                </td>
                                <td class="ErrorMessage">
                                    @Html.ValidationMessageFor(x => x.CourseCode)
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.CourseName)
                                </td>
                                <td>
                                    @Html.TextBoxFor(d => d.CourseName)
                                </td>
                                <td class="ErrorMessage">
                                    @Html.ValidationMessageFor(d => d.CourseName)
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.CourseCredit)
                                </td>
                                <td>
                                    @Html.TextBoxFor(d => d.CourseCredit)
                                </td>
                                <td class="ErrorMessage">
                                    @Html.ValidationMessageFor(d => d.CourseCredit)
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.Description)
                                </td>
                                <td>
                                    @Html.TextAreaFor(d => d.Description)
                                </td>
                                <td class="ErrorMessage">
                                    @Html.ValidationMessageFor(d => d.Description)
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(d => d.DeptId)
                                </td>
                                <td>
                                    <select name="DeptId" id="DeptId">
                                        <option value="">
                                            --Select One--  
                                        </option>
                                        @foreach (Department department in aDepartments)
                                        {
                                            <option value="@department.DeptId">@department.DeptCode</option>
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>@Html.LabelFor(d=>d.SemesterId)</td>
                                <td>
                                    <select name="SemesterId" id="SemesterId">
                                        <option value=""> --Select One--</option>
                                        @foreach (Semester semester in aSemesters)
                                        {
                                            <option value="@semester.SemesterId">@semester.SemesterName</option>
                                        }
                                    </select>
                                </td>

                            </tr>
                            <tr>
                                <td>
                                    <input type="submit" value="Save" />
                                    <label for="message" class=".message"></label>
                                    @message
                                </td>
                            </table>
                    </fieldset>
                </form>
            }
            <div class="clear"></div>

            <!--start footer from here-->
            <div id="footer">

            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>

UCRMS_MVC/Views/Course/UnAssignAllCourses.cshtml
@using System.ServiceModel.Channels
@using UCRMS_MVC.Models
@model UCRMS_MVC.Models.ViewResultByRegNo

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>UCRMS</title>
    <meta name="description" content="A description of your website">
    <meta name="keywords" content="keyword1, keyword2, keyword3">
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link href="~/Content/jquery.datepick.css" rel="stylesheet" />
    <style>
        .ErrorMessage {
            color: red;
            font-style: italic;
        }
    </style>
</head>
<body>

    <div id="wrapper">

        <div id="header">

            <div class="banner_img">
                <h1>University Course and Result Management System </h1>
            </div>

        </div>

        <div class="navigation navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Department", "Index", "Department")</li>
                <li>@Html.ActionLink("Course", "Index", "Course")</li>
                <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>
                <li>@Html.ActionLink("Student", "Index", "Student")</li>
                <li>@Html.ActionLink("Enroll Course", "Enroll", "Enroll")</li>
                <li>@Html.ActionLink("Allocate Rooms", "Index", "AllocateClassRoom")</li>
            </ul>
        </div>

        <div style="text-align: center;background: silver;font-size: larger;">
            <input id="UnallocateButton" type="button" value="Unallocate All Courses" style="width: 250px;height: 200px; margin: 20px auto;font-size: larger;" />
        </div>
        <div>
            <tr>
                <td>
                    @Html.ActionLink("Back", "Index", "Course")
                </td>
            </tr>
        </div>

    </div>
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $(document).ready(function () {
            $("#UnallocateButton").click(function () {
                var res = confirm("Are you sure to UnAssign Course info?");
                if (res == false) {
                    return false;
                } else {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("AjaxUnAssignAllCourses", "Course")',
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data) {
                                alert("All Courses has been UnAssign successfully.");
                            } else {
                                alert("Unable to UnAssign, try again.");
                            }
                        }
                    });
                }
            });
        });
    </script>
</body>
</html>